version: '3.9'

services:
    cache:
        image: redis
        command: redis-server --appendonly yes
        hostname: redis
        ports:
            - 6379:6379
        volumes:
            - ./data/redis:/data
    
    database:
        image: postgres
        command: postgres
        hostname: postgres
        ports:
            - 5432:5432
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_MULTIPLE_DATABASES: project, tests

    # api:
    #     container_name: product-api
    #     build: 
    #         context: .
    #     image: product-api
    #     depends_on:
    #         - cache
    #         - database
    #     ports:
    #         - 8080:8080
    #     environment:
    #         REDIS_HOST: localhost
    #         REDIS_PORT: 6379
    #     links:
    #         - cache
    #         - database
    #     volumes:
    #         - ./:src
        